export const EXERCISES = [
  { id: 1,  name: 'Bench Press',               primary: ['Chest'],       secondary: ['Triceps'] },
  { id: 2,  name: 'Incline Bench Press',        primary: ['Chest'],       secondary: ['Shoulders', 'Triceps'] },
  { id: 3,  name: 'Dumbbell Fly',              primary: ['Chest'],       secondary: [] },
  { id: 4,  name: 'Squat',                     primary: ['Quads'],       secondary: ['Hamstrings', 'Glutes'] },
  { id: 5,  name: 'Leg Press',                 primary: ['Quads'],       secondary: ['Hamstrings', 'Glutes'] },
  { id: 6,  name: 'Lunge',                     primary: ['Quads'],       secondary: ['Glutes'] },
  { id: 7,  name: 'Romanian Deadlift',          primary: ['Hamstrings'],  secondary: ['Glutes'] },
  { id: 8,  name: 'Leg Curl',                  primary: ['Hamstrings'],  secondary: [] },
  { id: 9,  name: 'Deadlift',                  primary: ['Back'],        secondary: ['Hamstrings', 'Glutes'] },
  { id: 10, name: 'Lat Pulldown',              primary: ['Back'],        secondary: ['Biceps'] },
  { id: 11, name: 'Pull-up',                   primary: ['Back'],        secondary: ['Biceps'] },
  { id: 12, name: 'Barbell Row',               primary: ['Back'],        secondary: ['Biceps'] },
  { id: 13, name: 'Seated Cable Row',          primary: ['Back'],        secondary: ['Biceps'] },
  { id: 14, name: 'Overhead Press',            primary: ['Shoulders'],   secondary: ['Triceps'] },
  { id: 15, name: 'Lateral Raise',             primary: ['Shoulders'],   secondary: [] },
  { id: 16, name: 'Face Pull',                 primary: ['Shoulders'],   secondary: [] },
  { id: 17, name: 'Barbell Curl',              primary: ['Biceps'],      secondary: [] },
  { id: 18, name: 'Dumbbell Curl',             primary: ['Biceps'],      secondary: [] },
  { id: 19, name: 'Hammer Curl',               primary: ['Biceps'],      secondary: [] },
  { id: 20, name: 'Tricep Pushdown',           primary: ['Triceps'],     secondary: [] },
  { id: 21, name: 'Skull Crusher',             primary: ['Triceps'],     secondary: [] },
  { id: 22, name: 'Overhead Tricep Extension', primary: ['Triceps'],     secondary: [] },
  { id: 23, name: 'Hip Thrust',                primary: ['Glutes'],      secondary: ['Hamstrings'] },
  { id: 24, name: 'Glute Bridge',              primary: ['Glutes'],      secondary: ['Hamstrings'] },
  { id: 25, name: 'Calf Raise',                primary: [],              secondary: [] },
  { id: 26, name: 'Plank',                     primary: [],              secondary: [] },
]
